# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-iam-role
  description: This component is responsible for provisioning simple IAM roles
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








